### PR TITLE
fix : Cannot use 'in' operator to search for '$ref' in null

### LINKED ISSUE #95: Exception when merging files with nullable enums
Command I'm running:

```
% npx openapi-merge-cli --config openapi-merge.yaml
```

Files i'm using:

File 1:
```
openapi: 3.0.3
info:
  title: Test
  version: 0.0.1
paths:
  /some/endpoint1:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/someSchema'
      responses:
        '200':
          description: successful operation
components:
  schemas:
    someSchema:
      type: object
      properties:
        someField:
          type: string
          nullable: true
          enum:
            - "A"
            - "B"
            - "C"
            - null
```

File 2 (identical to File 1, except for endpoint):
```
openapi: 3.0.3
info:
  title: Test
  version: 0.0.1
paths:
  /some/endpoint2:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/someSchema'
      responses:
        '200':
          description: successful operation
components:
  schemas:
    someSchema:
      type: object
      properties:
        someField:
          type: string
          nullable: true
          enum:
            - "A"
            - "B"
            - "C"
            - null
```

Output:
```
## /opt/homebrew/Cellar/node/20.8.0/bin/node: Running v1.3.1 (+1ms)
## Loaded the configuration: 2 inputs (+36ms)
## Loading input 0: specs/test1.yaml (+0ms)
## Loading input 1: specs/test2.yaml (+0ms)
## Loaded the inputs into memory, merging the results. (+1ms)
An uncaught exception was thrown TypeError: Cannot use 'in' operator to search for '$ref' in null
    at Object.isReference (/Users/.../node_modules/atlassian-openapi/lib/type-checks.js:85:48)
    at compare (/Users/.../node_modules/openapi-merge/dist/component-equivalence.js:63:51)
    at /Users/.../node_modules/openapi-merge/dist/component-equivalence.js:80:39
    at Array.every (<anonymous>)
    at compare (/Users/.../node_modules/openapi-merge/dist/component-equivalence.js:80:26)
    at /Users/.../node_modules/openapi-merge/dist/component-equivalence.js:80:39
    at Array.every (<anonymous>)
    at compare (/Users/.../node_modules/openapi-merge/dist/component-equivalence.js:80:26)
    at /Users/.../node_modules/openapi-merge/dist/component-equivalence.js:80:39
    at Array.every (<anonymous>)
```

Platform: macOS Ventura (22D49)  
Node version:

```
% /opt/homebrew/Cellar/node/20.8.0/bin/node -v
v20.8.0
```

### PR DESCRIPTION
**Pull request by jzyinq**
That fixes https://github.com/robertmassaioli/openapi-merge/issues/95

### CODE REVIEW

File: packages/openapi-merge/src/component-equivalence.ts [hunk 1]
```diff
@@ -72,17 +72,17 @@ export function deepEquality<A>(xLookup: Lookup.Lookup, yLookup: Lookup.Lookup):
 
   function compare<T>(x: T | Swagger.Reference, y: T | Swagger.Reference): boolean {
     // If both are references then look up the references and compare them for equality
-    if (TC.isReference(x) && TC.isReference(y)) {
+    if (x !== null && y !== null && TC.isReference(x) && TC.isReference(y)) {
```
Comment (robertmassaioli) [inline packages/openapi-merge/src/component-equivalence.ts:75]: For all Null checks in this repository we use the ts-is-present library, for consistency. Can you please swap to that? e.g. https://github.com/robertmassaioli/openapi-merge/blob/f625540217f7615091b0cb85fff5378d55e3ed65/packages/openapi-merge/src/index.ts#L1

File: packages/openapi-merge/src/component-equivalence.ts [hunk 2]
```diff
@@ -72,17 +72,17 @@ export function deepEquality<A>(xLookup: Lookup.Lookup, yLookup: Lookup.Lookup):
...
       if (refRecord.checkAndStore(x, y) === 'seen-before') {
         return true;
       }
 
       const xResult = isSchemaOrThrowError(x, xLookup.getSchema(x));
       const yResult = isSchemaOrThrowError(y, yLookup.getSchema(y));
       return compare(xResult, yResult);
-    } else if (TC.isReference(x) || TC.isReference(y)) {
+    } else if ((x !== null && TC.isReference(x)) || (y !== null && TC.isReference(y))) {
```
Comment (robertmassaioli) [inline packages/openapi-merge/src/component-equivalence.ts:83]: Please only perform this null check once for each variable instead of every time in each code block.

**Review by robertmassaioli — COMMENTED** [review]
I've reviewed this change and it broadly looks good. Thanks for the submission. Please make the fixes and I'll merge it in.

**Comment by jzyinq** [comment]
> I've reviewed this change and it broadly looks good. Thanks for the submission. Please make the fixes and I'll merge it in.

I applied your suggestions, I'm also very happy to see you here ;-) Tbh I thought this would be a stale PR and I'm full of joy that I will not have to twist my ankles with some fork magic around my project :magic_wand:

**Comment by jzyinq** [comment]
@robertmassaioli friendly reminder :)

**Comment by jzyinq** [comment]
@robertmassaioli So it seems I will have to deal with forking anyway - I hope you will find the time to merge it eventually.

**Comment by jzyinq** [comment]
Thank you!
